const FOODS = [
  {
    "name": "Silver Hills Bread",
    "category": "Bread",
    "serving": 40,
    "calories": 95,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 20,
    "fat": 0.5,
    "fiber": 2.5,
    "calcium": 80,
    "iron": 1,
    "potassium": 100,
    "selenium": 6,
    "omega3": 0,
    "note": "1 slice"
  },
  {
    "name": "Dempsters 12 Grain Bread",
    "category": "Bread",
    "serving": 40,
    "calories": 110,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 21,
    "fat": 1.5,
    "fiber": 3,
    "calcium": 90,
    "iron": 1,
    "potassium": 140,
    "selenium": 4,
    "omega3": 0,
    "note": "1 slice"
  },
  {
    "name": "Egg Whites Raw",
    "category": "Protein",
    "serving": 100,
    "calories": 50,
    "completeProtein": 11,
    "totalProtein": 11,
    "carbs": 1,
    "fat": 0,
    "fiber": 0,
    "calcium": 7,
    "iron": 0.1,
    "potassium": 160,
    "selenium": 20,
    "omega3": 0,
    "note": "Raw liquid weight"
  },
  {
    "name": "Boiled Egg Whites",
    "category": "Protein",
    "serving": 66,
    "calories": 34,
    "completeProtein": 7,
    "totalProtein": 7,
    "carbs": 0,
    "fat": 0,
    "fiber": 0,
    "calcium": 4,
    "iron": 0.1,
    "potassium": 100,
    "selenium": 13,
    "omega3": 0,
    "note": "2 egg whites"
  },
  {
    "name": "Chicken Breast Raw",
    "category": "Protein",
    "serving": 100,
    "calories": 120,
    "completeProtein": 23,
    "totalProtein": 23,
    "carbs": 0,
    "fat": 2.5,
    "fiber": 0,
    "calcium": 10,
    "iron": 0.8,
    "potassium": 220,
    "selenium": 20,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Chicken Breast Cooked",
    "category": "Protein",
    "serving": 100,
    "calories": 165,
    "completeProtein": 31,
    "totalProtein": 31,
    "carbs": 0,
    "fat": 3.5,
    "fiber": 0,
    "calcium": 15,
    "iron": 1,
    "potassium": 250,
    "selenium": 25,
    "omega3": 0,
    "note": "Cooked"
  },
  {
    "name": "Chicken Thigh Raw Boneless Skinless",
    "category": "Protein Fat",
    "serving": 100,
    "calories": 150,
    "completeProtein": 19,
    "totalProtein": 19,
    "carbs": 0,
    "fat": 8,
    "fiber": 0,
    "calcium": 10,
    "iron": 0.8,
    "potassium": 200,
    "selenium": 18,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Greek Yogurt Non Fat",
    "category": "Protein",
    "serving": 100,
    "calories": 60,
    "completeProtein": 10,
    "totalProtein": 10,
    "carbs": 4,
    "fat": 0,
    "fiber": 0,
    "calcium": 120,
    "iron": 0,
    "potassium": 150,
    "selenium": 3,
    "omega3": 0,
    "note": "Use label if different"
  },
  {
    "name": "Cottage Cheese",
    "category": "Protein",
    "serving": 100,
    "calories": 88,
    "completeProtein": 12,
    "totalProtein": 12,
    "carbs": 5,
    "fat": 2,
    "fiber": 0,
    "calcium": 120,
    "iron": 0.1,
    "potassium": 150,
    "selenium": 5,
    "omega3": 0,
    "note": "Your label based"
  },
  {
    "name": "Sardines Brunswick Golden Smoked",
    "category": "Protein Fat",
    "serving": 80,
    "calories": 100,
    "completeProtein": 14,
    "totalProtein": 14,
    "carbs": 0,
    "fat": 5,
    "fiber": 0,
    "calcium": 75,
    "iron": 1,
    "potassium": 250,
    "selenium": 40,
    "omega3": 0.8,
    "note": "Your label"
  },
  {
    "name": "Smoked Salmon",
    "category": "Protein Fat",
    "serving": 45,
    "calories": 70,
    "completeProtein": 10,
    "totalProtein": 10,
    "carbs": 0,
    "fat": 3,
    "fiber": 0,
    "calcium": 10,
    "iron": 0.3,
    "potassium": 250,
    "selenium": 15,
    "omega3": 0.4,
    "note": "Higher sodium"
  },
  {
    "name": "Skoulakis Chicken Souvlaki",
    "category": "Protein",
    "serving": 125,
    "calories": 180,
    "completeProtein": 27,
    "totalProtein": 27,
    "carbs": 2,
    "fat": 5,
    "fiber": 0,
    "calcium": 15,
    "iron": 1,
    "potassium": 350,
    "selenium": 20,
    "omega3": 0,
    "note": "1 skewer"
  },
  {
    "name": "Tofu Extra Firm Uncooked",
    "category": "Protein",
    "serving": 85,
    "calories": 70,
    "completeProtein": 8,
    "totalProtein": 8,
    "carbs": 2,
    "fat": 4,
    "fiber": 1,
    "calcium": 120,
    "iron": 1.5,
    "potassium": 120,
    "selenium": 8,
    "omega3": 0,
    "note": "Uncooked"
  },
  {
    "name": "Paneer",
    "category": "Protein Fat",
    "serving": 50,
    "calories": 135,
    "completeProtein": 9,
    "totalProtein": 9,
    "carbs": 2,
    "fat": 10,
    "fiber": 0,
    "calcium": 200,
    "iron": 0.2,
    "potassium": 40,
    "selenium": 3,
    "omega3": 0,
    "note": "Fat source"
  },
  {
    "name": "Soya Chunks Dry",
    "category": "Protein",
    "serving": 50,
    "calories": 170,
    "completeProtein": 26,
    "totalProtein": 26,
    "carbs": 13,
    "fat": 1,
    "fiber": 8,
    "calcium": 150,
    "iron": 5,
    "potassium": 300,
    "selenium": 5,
    "omega3": 0,
    "note": "Dry weight"
  },
  {
    "name": "Ponni Rice Cooked",
    "category": "Carb",
    "serving": 80,
    "calories": 105,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 23,
    "fat": 0.2,
    "fiber": 0.5,
    "calcium": 5,
    "iron": 0.2,
    "potassium": 30,
    "selenium": 1,
    "omega3": 0,
    "note": "Cooked"
  },
  {
    "name": "Dosa",
    "category": "South Indian Breakfast",
    "serving": 100,
    "calories": 180,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 32,
    "fat": 4,
    "fiber": 2,
    "calcium": 20,
    "iron": 1,
    "potassium": 120,
    "selenium": 2,
    "omega3": 0,
    "note": "Oil dependent"
  },
  {
    "name": "Idli",
    "category": "South Indian Breakfast",
    "serving": 50,
    "calories": 70,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 14,
    "fat": 0.5,
    "fiber": 1,
    "calcium": 8,
    "iron": 0.5,
    "potassium": 40,
    "selenium": 1,
    "omega3": 0,
    "note": "1 medium"
  },
  {
    "name": "Ven Pongal",
    "category": "South Indian Breakfast",
    "serving": 100,
    "calories": 190,
    "completeProtein": 5,
    "totalProtein": 5,
    "carbs": 27,
    "fat": 7,
    "fiber": 2,
    "calcium": 20,
    "iron": 1,
    "potassium": 120,
    "selenium": 2,
    "omega3": 0,
    "note": "Ghee dependent"
  },
  {
    "name": "Kara Chutney",
    "category": "Condiment",
    "serving": 30,
    "calories": 45,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 4,
    "fat": 2,
    "fiber": 1,
    "calcium": 10,
    "iron": 0.5,
    "potassium": 80,
    "selenium": 1,
    "omega3": 0,
    "note": "Oil dependent"
  },
  {
    "name": "Sambar",
    "category": "Curry",
    "serving": 100,
    "calories": 60,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 8,
    "fat": 2,
    "fiber": 2,
    "calcium": 30,
    "iron": 1,
    "potassium": 140,
    "selenium": 2,
    "omega3": 0,
    "note": "Dal amount varies"
  },
  {
    "name": "Kara Kuzhambu",
    "category": "Curry",
    "serving": 100,
    "calories": 90,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 8,
    "fat": 5,
    "fiber": 2,
    "calcium": 25,
    "iron": 1,
    "potassium": 150,
    "selenium": 1,
    "omega3": 0,
    "note": "Oil dependent"
  },
  {
    "name": "Chicken Pulusu",
    "category": "Curry",
    "serving": 100,
    "calories": 140,
    "completeProtein": 16,
    "totalProtein": 16,
    "carbs": 5,
    "fat": 6,
    "fiber": 1,
    "calcium": 20,
    "iron": 1.2,
    "potassium": 220,
    "selenium": 15,
    "omega3": 0,
    "note": "Oil and cut vary"
  },
  {
    "name": "Mutton Pulusu",
    "category": "Curry",
    "serving": 100,
    "calories": 190,
    "completeProtein": 16,
    "totalProtein": 16,
    "carbs": 4,
    "fat": 12,
    "fiber": 0,
    "calcium": 18,
    "iron": 1.8,
    "potassium": 240,
    "selenium": 20,
    "omega3": 0,
    "note": "Higher fat"
  },
  {
    "name": "Fish Pulusu",
    "category": "Curry",
    "serving": 100,
    "calories": 130,
    "completeProtein": 18,
    "totalProtein": 18,
    "carbs": 4,
    "fat": 5,
    "fiber": 0,
    "calcium": 20,
    "iron": 1,
    "potassium": 210,
    "selenium": 25,
    "omega3": 0.4,
    "note": "Fish varies"
  },
  {
    "name": "Golden Pomfret Air Fry",
    "category": "Protein Fat",
    "serving": 100,
    "calories": 170,
    "completeProtein": 22,
    "totalProtein": 22,
    "carbs": 1,
    "fat": 8,
    "fiber": 0,
    "calcium": 25,
    "iron": 1,
    "potassium": 280,
    "selenium": 35,
    "omega3": 0.6,
    "note": "Oil dependent"
  },
  {
    "name": "Beans Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 80,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 10,
    "fat": 3,
    "fiber": 4,
    "calcium": 40,
    "iron": 1.5,
    "potassium": 180,
    "selenium": 1,
    "omega3": 0,
    "note": "Oil dependent"
  },
  {
    "name": "Karamani Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 110,
    "completeProtein": 5,
    "totalProtein": 5,
    "carbs": 14,
    "fat": 3,
    "fiber": 5,
    "calcium": 45,
    "iron": 2,
    "potassium": 200,
    "selenium": 1,
    "omega3": 0,
    "note": "Bean based"
  },
  {
    "name": "Okra Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 90,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 10,
    "fat": 4,
    "fiber": 4,
    "calcium": 50,
    "iron": 1,
    "potassium": 180,
    "selenium": 1,
    "omega3": 0,
    "note": "Oil dependent"
  },
  {
    "name": "Valor Beans Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 95,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 12,
    "fat": 3,
    "fiber": 5,
    "calcium": 40,
    "iron": 1.5,
    "potassium": 190,
    "selenium": 1,
    "omega3": 0,
    "note": "Oil dependent"
  },
  {
    "name": "Cabbage Tava Fry",
    "category": "Poriyal",
    "serving": 100,
    "calories": 60,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 8,
    "fat": 2,
    "fiber": 3,
    "calcium": 40,
    "iron": 0.5,
    "potassium": 170,
    "selenium": 1,
    "omega3": 0,
    "note": "Low oil"
  },
  {
    "name": "Spinach Curry With Pappu",
    "category": "Curry",
    "serving": 100,
    "calories": 95,
    "completeProtein": 5,
    "totalProtein": 5,
    "carbs": 10,
    "fat": 3,
    "fiber": 3,
    "calcium": 110,
    "iron": 2.5,
    "potassium": 250,
    "selenium": 2,
    "omega3": 0,
    "note": "Dal adds protein"
  },
  {
    "name": "Spinach Curry Without Pappu",
    "category": "Curry",
    "serving": 100,
    "calories": 55,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 5,
    "fat": 2,
    "fiber": 3,
    "calcium": 120,
    "iron": 2.5,
    "potassium": 250,
    "selenium": 2,
    "omega3": 0,
    "note": "Lower calorie"
  },
  {
    "name": "Snake Gourd Channa Dal Curry",
    "category": "Curry",
    "serving": 100,
    "calories": 120,
    "completeProtein": 5,
    "totalProtein": 5,
    "carbs": 14,
    "fat": 4,
    "fiber": 4,
    "calcium": 40,
    "iron": 1.5,
    "potassium": 180,
    "selenium": 2,
    "omega3": 0,
    "note": "Dal adds carbs"
  },
  {
    "name": "Guacamole",
    "category": "Fat",
    "serving": 35,
    "calories": 60,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 3,
    "fat": 5,
    "fiber": 3,
    "calcium": 10,
    "iron": 0.5,
    "potassium": 120,
    "selenium": 0,
    "omega3": 0,
    "note": "Fat add on"
  },
  {
    "name": "Peanut Butter",
    "category": "Fat",
    "serving": 16,
    "calories": 95,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 3,
    "fat": 8,
    "fiber": 1,
    "calcium": 10,
    "iron": 0.5,
    "potassium": 90,
    "selenium": 1,
    "omega3": 0,
    "note": "Easy to overeat"
  },
  {
    "name": "Chia Seeds",
    "category": "Seed",
    "serving": 5,
    "calories": 25,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 2,
    "fat": 1.5,
    "fiber": 2,
    "calcium": 30,
    "iron": 0.4,
    "potassium": 20,
    "selenium": 1,
    "omega3": 0.9,
    "note": "Drink add on"
  },
  {
    "name": "Almonds",
    "category": "Nut",
    "serving": 5,
    "calories": 29,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 1,
    "fat": 2.5,
    "fiber": 0.6,
    "calcium": 13,
    "iron": 0.2,
    "potassium": 36,
    "selenium": 0,
    "omega3": 0,
    "note": "Portion controlled"
  },
  {
    "name": "Walnuts",
    "category": "Nut",
    "serving": 5,
    "calories": 33,
    "completeProtein": 0.8,
    "totalProtein": 0.8,
    "carbs": 0.7,
    "fat": 3.3,
    "fiber": 0.3,
    "calcium": 5,
    "iron": 0.1,
    "potassium": 22,
    "selenium": 0,
    "omega3": 0.45,
    "note": "Omega fats"
  },
  {
    "name": "Brazil Nut",
    "category": "Nut",
    "serving": 5,
    "calories": 33,
    "completeProtein": 0.7,
    "totalProtein": 0.7,
    "carbs": 0.6,
    "fat": 3.3,
    "fiber": 0.4,
    "calcium": 8,
    "iron": 0.1,
    "potassium": 33,
    "selenium": 95,
    "omega3": 0,
    "note": "1 nut"
  },
  {
    "name": "Pumpkin Seeds",
    "category": "Seed",
    "serving": 5,
    "calories": 28,
    "completeProtein": 1.5,
    "totalProtein": 1.5,
    "carbs": 1,
    "fat": 2,
    "fiber": 0.5,
    "calcium": 3,
    "iron": 0.4,
    "potassium": 40,
    "selenium": 0,
    "omega3": 0,
    "note": "Mineral add on"
  },
  {
    "name": "Orange",
    "category": "Fruit",
    "serving": 100,
    "calories": 47,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 12,
    "fat": 0,
    "fiber": 2.5,
    "calcium": 40,
    "iron": 0.1,
    "potassium": 180,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Grapefruit",
    "category": "Fruit",
    "serving": 100,
    "calories": 42,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 10,
    "fat": 0,
    "fiber": 1.5,
    "calcium": 20,
    "iron": 0.1,
    "potassium": 135,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Strawberries",
    "category": "Fruit",
    "serving": 100,
    "calories": 32,
    "completeProtein": 0.7,
    "totalProtein": 0.7,
    "carbs": 8,
    "fat": 0.3,
    "fiber": 2,
    "calcium": 16,
    "iron": 0.4,
    "potassium": 153,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Blueberries",
    "category": "Fruit",
    "serving": 100,
    "calories": 57,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 14,
    "fat": 0,
    "fiber": 2.5,
    "calcium": 6,
    "iron": 0.3,
    "potassium": 77,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Blackberries",
    "category": "Fruit",
    "serving": 35,
    "calories": 15,
    "completeProtein": 0.5,
    "totalProtein": 0.5,
    "carbs": 3,
    "fat": 0,
    "fiber": 2,
    "calcium": 10,
    "iron": 0.2,
    "potassium": 60,
    "selenium": 0,
    "omega3": 0,
    "note": "Your serving"
  },
  {
    "name": "Kiwi",
    "category": "Fruit",
    "serving": 100,
    "calories": 61,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 15,
    "fat": 0.5,
    "fiber": 3,
    "calcium": 34,
    "iron": 0.3,
    "potassium": 312,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Grapes",
    "category": "Fruit",
    "serving": 100,
    "calories": 69,
    "completeProtein": 0.7,
    "totalProtein": 0.7,
    "carbs": 18,
    "fat": 0.2,
    "fiber": 1,
    "calcium": 10,
    "iron": 0.4,
    "potassium": 190,
    "selenium": 0,
    "omega3": 0,
    "note": "Easy to overeat"
  },
  {
    "name": "Gold Standard Whey",
    "category": "Supplement",
    "serving": 32,
    "calories": 120,
    "completeProtein": 24,
    "totalProtein": 24,
    "carbs": 3,
    "fat": 1,
    "fiber": 0,
    "calcium": 130,
    "iron": 0.9,
    "potassium": 200,
    "selenium": 0,
    "omega3": 0,
    "note": "1 scoop"
  },
  {
    "name": "Collagen Organika",
    "category": "Supplement",
    "serving": 10,
    "calories": 35,
    "completeProtein": 0,
    "totalProtein": 9,
    "carbs": 0,
    "fat": 0,
    "fiber": 0,
    "calcium": 0,
    "iron": 0,
    "potassium": 0,
    "selenium": 0,
    "omega3": 0,
    "note": "Incomplete protein"
  }
];
