const FOODS = [
  {
    "name": "Silver Hills Bread",
    "category": "Bread",
    "serving": 40,
    "calories": 95,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 20,
    "fat": 0.5,
    "fiber": 2.5,
    "calcium": 80,
    "iron": 1,
    "potassium": 100,
    "selenium": 6,
    "omega3": 0,
    "note": "1 slice"
  },
  {
    "name": "Dempsters 12 Grain Bread",
    "category": "Bread",
    "serving": 40,
    "calories": 110,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 21,
    "fat": 1.5,
    "fiber": 3,
    "calcium": 90,
    "iron": 1,
    "potassium": 140,
    "selenium": 4,
    "omega3": 0,
    "note": "1 slice"
  },
  {
    "name": "Egg Whites Raw",
    "category": "Protein",
    "serving": 100,
    "calories": 50,
    "completeProtein": 11,
    "totalProtein": 11,
    "carbs": 1,
    "fat": 0,
    "fiber": 0,
    "calcium": 7,
    "iron": 0.1,
    "potassium": 160,
    "selenium": 20,
    "omega3": 0,
    "note": "Raw liquid weight"
  },
  {
    "name": "Boiled Egg Whites",
    "category": "Protein",
    "serving": 66,
    "calories": 34,
    "completeProtein": 7,
    "totalProtein": 7,
    "carbs": 0,
    "fat": 0,
    "fiber": 0,
    "calcium": 4,
    "iron": 0.1,
    "potassium": 100,
    "selenium": 13,
    "omega3": 0,
    "note": "2 egg whites"
  },
  {
    "name": "Extra Large Boiled Egg White",
    "category": "Protein",
    "serving": 37,
    "calories": 19,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 0,
    "fat": 0,
    "fiber": 0,
    "calcium": 2,
    "iron": 0.1,
    "potassium": 56,
    "selenium": 7,
    "omega3": 0,
    "note": "1 extra large egg white, boiled"
  },
  {
    "name": "Chicken Breast Raw",
    "category": "Protein",
    "serving": 100,
    "calories": 120,
    "completeProtein": 23,
    "totalProtein": 23,
    "carbs": 0,
    "fat": 2.5,
    "fiber": 0,
    "calcium": 10,
    "iron": 0.8,
    "potassium": 220,
    "selenium": 20,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Chicken Breast Cooked",
    "category": "Protein",
    "serving": 100,
    "calories": 165,
    "completeProtein": 31,
    "totalProtein": 31,
    "carbs": 0,
    "fat": 3.5,
    "fiber": 0,
    "calcium": 15,
    "iron": 1,
    "potassium": 250,
    "selenium": 25,
    "omega3": 0,
    "note": "Cooked"
  },
  {
    "name": "Chicken Thigh Raw Boneless Skinless",
    "category": "Protein Fat",
    "serving": 100,
    "calories": 150,
    "completeProtein": 19,
    "totalProtein": 19,
    "carbs": 0,
    "fat": 8,
    "fiber": 0,
    "calcium": 10,
    "iron": 0.8,
    "potassium": 200,
    "selenium": 18,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Top Sirloin Steak Raw",
    "category": "Protein Fat",
    "serving": 100,
    "calories": 142,
    "completeProtein": 21,
    "totalProtein": 21,
    "carbs": 0,
    "fat": 6,
    "fiber": 0,
    "calcium": 12,
    "iron": 1.7,
    "potassium": 320,
    "selenium": 24,
    "omega3": 0,
    "note": "Raw weight",
    "servingLabel": "100g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Ribeye Steak Raw",
    "category": "Protein Fat",
    "serving": 100,
    "calories": 232,
    "completeProtein": 19,
    "totalProtein": 19,
    "carbs": 0,
    "fat": 17,
    "fiber": 0,
    "calcium": 10,
    "iron": 1.8,
    "potassium": 300,
    "selenium": 22,
    "omega3": 0,
    "note": "Raw weight, higher fat",
    "servingLabel": "100g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Beef Tenderloin Steak Raw",
    "category": "Protein Fat",
    "serving": 100,
    "calories": 170,
    "completeProtein": 21,
    "totalProtein": 21,
    "carbs": 0,
    "fat": 9,
    "fiber": 0,
    "calcium": 11,
    "iron": 1.9,
    "potassium": 330,
    "selenium": 24,
    "omega3": 0,
    "note": "Raw weight",
    "servingLabel": "100g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Striploin Steak Raw",
    "category": "Protein Fat",
    "serving": 100,
    "calories": 177,
    "completeProtein": 21,
    "totalProtein": 21,
    "carbs": 0,
    "fat": 10,
    "fiber": 0,
    "calcium": 10,
    "iron": 1.8,
    "potassium": 320,
    "selenium": 24,
    "omega3": 0,
    "note": "Raw weight",
    "servingLabel": "100g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Ground Beef Extra Lean Raw",
    "category": "Protein Fat",
    "serving": 100,
    "calories": 137,
    "completeProtein": 21,
    "totalProtein": 21,
    "carbs": 0,
    "fat": 5,
    "fiber": 0,
    "calcium": 12,
    "iron": 2.1,
    "potassium": 330,
    "selenium": 20,
    "omega3": 0,
    "note": "Raw weight",
    "servingLabel": "100g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Steak Cooked Generic",
    "category": "Protein Fat",
    "serving": 100,
    "calories": 220,
    "completeProtein": 29,
    "totalProtein": 29,
    "carbs": 0,
    "fat": 11,
    "fiber": 0,
    "calcium": 15,
    "iron": 2.4,
    "potassium": 360,
    "selenium": 30,
    "omega3": 0,
    "note": "Cooked weight",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Greek Yogurt Non Fat",
    "category": "Protein",
    "serving": 100,
    "calories": 60,
    "completeProtein": 10,
    "totalProtein": 10,
    "carbs": 4,
    "fat": 0,
    "fiber": 0,
    "calcium": 120,
    "iron": 0,
    "potassium": 150,
    "selenium": 3,
    "omega3": 0,
    "note": "Use label if different"
  },
  {
    "name": "Cottage Cheese",
    "category": "Protein",
    "serving": 100,
    "calories": 88,
    "completeProtein": 12,
    "totalProtein": 12,
    "carbs": 5,
    "fat": 2,
    "fiber": 0,
    "calcium": 120,
    "iron": 0.1,
    "potassium": 150,
    "selenium": 5,
    "omega3": 0,
    "note": "Your label based"
  },
  {
    "name": "Sardines Brunswick Golden Smoked",
    "category": "Protein Fat",
    "serving": 80,
    "calories": 100,
    "completeProtein": 14,
    "totalProtein": 14,
    "carbs": 0,
    "fat": 5,
    "fiber": 0,
    "calcium": 75,
    "iron": 1,
    "potassium": 250,
    "selenium": 40,
    "omega3": 0.8,
    "note": "Your label"
  },
  {
    "name": "Smoked Salmon",
    "category": "Protein Fat",
    "serving": 45,
    "calories": 70,
    "completeProtein": 10,
    "totalProtein": 10,
    "carbs": 0,
    "fat": 3,
    "fiber": 0,
    "calcium": 10,
    "iron": 0.3,
    "potassium": 250,
    "selenium": 15,
    "omega3": 0.4,
    "note": "Higher sodium"
  },
  {
    "name": "Skoulakis Chicken Souvlaki",
    "category": "Protein",
    "serving": 125,
    "calories": 180,
    "completeProtein": 27,
    "totalProtein": 27,
    "carbs": 2,
    "fat": 5,
    "fiber": 0,
    "calcium": 15,
    "iron": 1,
    "potassium": 350,
    "selenium": 20,
    "omega3": 0,
    "note": "1 skewer"
  },
  {
    "name": "Tofu Extra Firm Uncooked",
    "category": "Protein",
    "serving": 85,
    "calories": 70,
    "completeProtein": 8,
    "totalProtein": 8,
    "carbs": 2,
    "fat": 4,
    "fiber": 1,
    "calcium": 120,
    "iron": 1.5,
    "potassium": 120,
    "selenium": 8,
    "omega3": 0,
    "note": "Uncooked"
  },
  {
    "name": "Paneer",
    "category": "Protein Fat",
    "serving": 50,
    "calories": 135,
    "completeProtein": 9,
    "totalProtein": 9,
    "carbs": 2,
    "fat": 10,
    "fiber": 0,
    "calcium": 200,
    "iron": 0.2,
    "potassium": 40,
    "selenium": 3,
    "omega3": 0,
    "note": "Fat source"
  },
  {
    "name": "Soya Chunks Dry",
    "category": "Protein",
    "serving": 50,
    "calories": 170,
    "completeProtein": 26,
    "totalProtein": 26,
    "carbs": 13,
    "fat": 1,
    "fiber": 8,
    "calcium": 150,
    "iron": 5,
    "potassium": 300,
    "selenium": 5,
    "omega3": 0,
    "note": "Dry weight"
  },
  {
    "name": "Masoor Dal Cooked",
    "category": "Legume",
    "serving": 100,
    "calories": 116,
    "completeProtein": 9,
    "totalProtein": 9,
    "carbs": 20,
    "fat": 0.4,
    "fiber": 8,
    "calcium": 19,
    "iron": 3.3,
    "potassium": 369,
    "selenium": 3,
    "omega3": 0,
    "note": "Cooked lentils, plain",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Moong Dal Cooked",
    "category": "Legume",
    "serving": 100,
    "calories": 105,
    "completeProtein": 7,
    "totalProtein": 7,
    "carbs": 19,
    "fat": 0.4,
    "fiber": 7.6,
    "calcium": 27,
    "iron": 1.4,
    "potassium": 266,
    "selenium": 2,
    "omega3": 0,
    "note": "Cooked mung dal, plain",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Chana Dal Cooked",
    "category": "Legume",
    "serving": 100,
    "calories": 164,
    "completeProtein": 9,
    "totalProtein": 9,
    "carbs": 27,
    "fat": 2.6,
    "fiber": 8,
    "calcium": 49,
    "iron": 2.9,
    "potassium": 291,
    "selenium": 3,
    "omega3": 0,
    "note": "Cooked split chickpeas, plain",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Chickpeas Cooked",
    "category": "Legume",
    "serving": 100,
    "calories": 164,
    "completeProtein": 9,
    "totalProtein": 9,
    "carbs": 27,
    "fat": 2.6,
    "fiber": 7.6,
    "calcium": 49,
    "iron": 2.9,
    "potassium": 291,
    "selenium": 4,
    "omega3": 0,
    "note": "Cooked, plain",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Rajma Cooked",
    "category": "Legume",
    "serving": 100,
    "calories": 127,
    "completeProtein": 8.7,
    "totalProtein": 8.7,
    "carbs": 23,
    "fat": 0.5,
    "fiber": 6.4,
    "calcium": 28,
    "iron": 2.9,
    "potassium": 405,
    "selenium": 1,
    "omega3": 0,
    "note": "Kidney beans cooked, plain",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Besan Chilla",
    "category": "South Indian Breakfast",
    "serving": 100,
    "calories": 180,
    "completeProtein": 8,
    "totalProtein": 8,
    "carbs": 24,
    "fat": 5,
    "fiber": 5,
    "calcium": 35,
    "iron": 2,
    "potassium": 260,
    "selenium": 3,
    "omega3": 0,
    "note": "Chickpea flour pancake, oil dependent",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Ponni Rice Cooked",
    "category": "Carb",
    "serving": 80,
    "calories": 105,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 23,
    "fat": 0.2,
    "fiber": 0.5,
    "calcium": 5,
    "iron": 0.2,
    "potassium": 30,
    "selenium": 1,
    "omega3": 0,
    "note": "Cooked"
  },
  {
    "name": "Dosa",
    "category": "South Indian Breakfast",
    "serving": 100,
    "calories": 180,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 32,
    "fat": 4,
    "fiber": 2,
    "calcium": 20,
    "iron": 1,
    "potassium": 120,
    "selenium": 2,
    "omega3": 0,
    "note": "Oil dependent"
  },
  {
    "name": "Idli",
    "category": "South Indian Breakfast",
    "serving": 50,
    "calories": 70,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 14,
    "fat": 0.5,
    "fiber": 1,
    "calcium": 8,
    "iron": 0.5,
    "potassium": 40,
    "selenium": 1,
    "omega3": 0,
    "note": "1 medium"
  },
  {
    "name": "Ven Pongal",
    "category": "South Indian Breakfast",
    "serving": 100,
    "calories": 190,
    "completeProtein": 5,
    "totalProtein": 5,
    "carbs": 27,
    "fat": 7,
    "fiber": 2,
    "calcium": 20,
    "iron": 1,
    "potassium": 120,
    "selenium": 2,
    "omega3": 0,
    "note": "Ghee dependent"
  },
  {
    "name": "Kara Chutney",
    "category": "Condiment",
    "serving": 30,
    "calories": 45,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 4,
    "fat": 2,
    "fiber": 1,
    "calcium": 10,
    "iron": 0.5,
    "potassium": 80,
    "selenium": 1,
    "omega3": 0,
    "note": "Oil dependent"
  },
  {
    "name": "Sambar",
    "category": "Curry",
    "serving": 100,
    "calories": 60,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 8,
    "fat": 2,
    "fiber": 2,
    "calcium": 30,
    "iron": 1,
    "potassium": 140,
    "selenium": 2,
    "omega3": 0,
    "note": "Dal amount varies"
  },
  {
    "name": "Kara Kuzhambu",
    "category": "Curry",
    "serving": 100,
    "calories": 90,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 8,
    "fat": 5,
    "fiber": 2,
    "calcium": 25,
    "iron": 1,
    "potassium": 150,
    "selenium": 1,
    "omega3": 0,
    "note": "Oil dependent"
  },
  {
    "name": "Chicken Pulusu",
    "category": "Curry",
    "serving": 100,
    "calories": 140,
    "completeProtein": 16,
    "totalProtein": 16,
    "carbs": 5,
    "fat": 6,
    "fiber": 1,
    "calcium": 20,
    "iron": 1.2,
    "potassium": 220,
    "selenium": 15,
    "omega3": 0,
    "note": "Oil and cut vary"
  },
  {
    "name": "Mutton Pulusu",
    "category": "Curry",
    "serving": 100,
    "calories": 190,
    "completeProtein": 16,
    "totalProtein": 16,
    "carbs": 4,
    "fat": 12,
    "fiber": 0,
    "calcium": 18,
    "iron": 1.8,
    "potassium": 240,
    "selenium": 20,
    "omega3": 0,
    "note": "Higher fat"
  },
  {
    "name": "Fish Pulusu",
    "category": "Curry",
    "serving": 100,
    "calories": 130,
    "completeProtein": 18,
    "totalProtein": 18,
    "carbs": 4,
    "fat": 5,
    "fiber": 0,
    "calcium": 20,
    "iron": 1,
    "potassium": 210,
    "selenium": 25,
    "omega3": 0.4,
    "note": "Fish varies"
  },
  {
    "name": "Golden Pomfret Air Fry",
    "category": "Protein Fat",
    "serving": 100,
    "calories": 170,
    "completeProtein": 22,
    "totalProtein": 22,
    "carbs": 1,
    "fat": 8,
    "fiber": 0,
    "calcium": 25,
    "iron": 1,
    "potassium": 280,
    "selenium": 35,
    "omega3": 0.6,
    "note": "Oil dependent"
  },
  {
    "name": "Beans Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 80,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 10,
    "fat": 3,
    "fiber": 4,
    "calcium": 40,
    "iron": 1.5,
    "potassium": 180,
    "selenium": 1,
    "omega3": 0,
    "note": "Oil dependent"
  },
  {
    "name": "Karamani Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 110,
    "completeProtein": 5,
    "totalProtein": 5,
    "carbs": 14,
    "fat": 3,
    "fiber": 5,
    "calcium": 45,
    "iron": 2,
    "potassium": 200,
    "selenium": 1,
    "omega3": 0,
    "note": "Bean based"
  },
  {
    "name": "Okra Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 90,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 10,
    "fat": 4,
    "fiber": 4,
    "calcium": 50,
    "iron": 1,
    "potassium": 180,
    "selenium": 1,
    "omega3": 0,
    "note": "Oil dependent"
  },
  {
    "name": "Valor Beans Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 95,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 12,
    "fat": 3,
    "fiber": 5,
    "calcium": 40,
    "iron": 1.5,
    "potassium": 190,
    "selenium": 1,
    "omega3": 0,
    "note": "Oil dependent"
  },
  {
    "name": "Beetroot Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 95,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 13,
    "fat": 4,
    "fiber": 4,
    "calcium": 25,
    "iron": 0.8,
    "potassium": 260,
    "selenium": 1,
    "omega3": 0,
    "note": "Beetroot coconut poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Carrot Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 90,
    "completeProtein": 1.5,
    "totalProtein": 1.5,
    "carbs": 11,
    "fat": 4,
    "fiber": 3.5,
    "calcium": 35,
    "iron": 0.5,
    "potassium": 250,
    "selenium": 1,
    "omega3": 0,
    "note": "Carrot coconut poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Carrot Beans Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 85,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 10,
    "fat": 4,
    "fiber": 4,
    "calcium": 35,
    "iron": 0.8,
    "potassium": 230,
    "selenium": 1,
    "omega3": 0,
    "note": "Carrot beans coconut poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Potato Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 150,
    "completeProtein": 2.5,
    "totalProtein": 2.5,
    "carbs": 24,
    "fat": 5,
    "fiber": 3,
    "calcium": 15,
    "iron": 0.8,
    "potassium": 420,
    "selenium": 1,
    "omega3": 0,
    "note": "Aloo potato poriyal estimate, oil dependent",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Brinjal Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 95,
    "completeProtein": 1.5,
    "totalProtein": 1.5,
    "carbs": 8,
    "fat": 6,
    "fiber": 4,
    "calcium": 25,
    "iron": 0.6,
    "potassium": 210,
    "selenium": 1,
    "omega3": 0,
    "note": "Kathirikai poriyal estimate, oil dependent",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Kovakkai Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 90,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 9,
    "fat": 5,
    "fiber": 4,
    "calcium": 35,
    "iron": 1,
    "potassium": 200,
    "selenium": 1,
    "omega3": 0,
    "note": "Ivy gourd poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Chow Chow Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 75,
    "completeProtein": 1.5,
    "totalProtein": 1.5,
    "carbs": 8,
    "fat": 4,
    "fiber": 3,
    "calcium": 25,
    "iron": 0.5,
    "potassium": 160,
    "selenium": 1,
    "omega3": 0,
    "note": "Chayote poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Bottle Gourd Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 70,
    "completeProtein": 1.5,
    "totalProtein": 1.5,
    "carbs": 7,
    "fat": 4,
    "fiber": 2.5,
    "calcium": 25,
    "iron": 0.5,
    "potassium": 170,
    "selenium": 1,
    "omega3": 0,
    "note": "Sorakkai poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Snake Gourd Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 75,
    "completeProtein": 1.5,
    "totalProtein": 1.5,
    "carbs": 8,
    "fat": 4,
    "fiber": 3,
    "calcium": 35,
    "iron": 0.6,
    "potassium": 180,
    "selenium": 1,
    "omega3": 0,
    "note": "Pudalangai poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Bitter Gourd Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 85,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 9,
    "fat": 4,
    "fiber": 4,
    "calcium": 30,
    "iron": 0.8,
    "potassium": 300,
    "selenium": 1,
    "omega3": 0,
    "note": "Pavakkai poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Raw Banana Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 145,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 27,
    "fat": 4,
    "fiber": 4,
    "calcium": 15,
    "iron": 0.8,
    "potassium": 420,
    "selenium": 1,
    "omega3": 0,
    "note": "Vazhakkai poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Plantain Stem Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 70,
    "completeProtein": 1.5,
    "totalProtein": 1.5,
    "carbs": 8,
    "fat": 3,
    "fiber": 5,
    "calcium": 35,
    "iron": 0.7,
    "potassium": 250,
    "selenium": 1,
    "omega3": 0,
    "note": "Vazhaithandu poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Cauliflower Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 90,
    "completeProtein": 2.5,
    "totalProtein": 2.5,
    "carbs": 8,
    "fat": 5,
    "fiber": 3,
    "calcium": 30,
    "iron": 0.7,
    "potassium": 220,
    "selenium": 1,
    "omega3": 0,
    "note": "Cauliflower poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Broccoli Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 85,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 8,
    "fat": 4,
    "fiber": 4,
    "calcium": 50,
    "iron": 1,
    "potassium": 300,
    "selenium": 2,
    "omega3": 0,
    "note": "Broccoli poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Cabbage Tava Fry",
    "category": "Poriyal",
    "serving": 100,
    "calories": 60,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 8,
    "fat": 2,
    "fiber": 3,
    "calcium": 40,
    "iron": 0.5,
    "potassium": 170,
    "selenium": 1,
    "omega3": 0,
    "note": "Low oil"
  },
  {
    "name": "Spinach Curry With Pappu",
    "category": "Curry",
    "serving": 100,
    "calories": 95,
    "completeProtein": 5,
    "totalProtein": 5,
    "carbs": 10,
    "fat": 3,
    "fiber": 3,
    "calcium": 110,
    "iron": 2.5,
    "potassium": 250,
    "selenium": 2,
    "omega3": 0,
    "note": "Dal adds protein"
  },
  {
    "name": "Spinach Curry Without Pappu",
    "category": "Curry",
    "serving": 100,
    "calories": 55,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 5,
    "fat": 2,
    "fiber": 3,
    "calcium": 120,
    "iron": 2.5,
    "potassium": 250,
    "selenium": 2,
    "omega3": 0,
    "note": "Lower calorie"
  },
  {
    "name": "Snake Gourd Channa Dal Curry",
    "category": "Curry",
    "serving": 100,
    "calories": 120,
    "completeProtein": 5,
    "totalProtein": 5,
    "carbs": 14,
    "fat": 4,
    "fiber": 4,
    "calcium": 40,
    "iron": 1.5,
    "potassium": 180,
    "selenium": 2,
    "omega3": 0,
    "note": "Dal adds carbs"
  },
  {
    "name": "Guacamole",
    "category": "Fat",
    "serving": 35,
    "calories": 60,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 3,
    "fat": 5,
    "fiber": 3,
    "calcium": 10,
    "iron": 0.5,
    "potassium": 120,
    "selenium": 0,
    "omega3": 0,
    "note": "Fat add on"
  },
  {
    "name": "Peanut Butter",
    "category": "Fat",
    "serving": 16,
    "calories": 95,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 3,
    "fat": 8,
    "fiber": 1,
    "calcium": 10,
    "iron": 0.5,
    "potassium": 90,
    "selenium": 1,
    "omega3": 0,
    "note": "Easy to overeat"
  },
  {
    "name": "Chia Seeds",
    "category": "Seed",
    "serving": 5,
    "calories": 25,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 2,
    "fat": 1.5,
    "fiber": 2,
    "calcium": 30,
    "iron": 0.4,
    "potassium": 20,
    "selenium": 1,
    "omega3": 0.9,
    "note": "Drink add on"
  },
  {
    "name": "Almonds",
    "category": "Nut",
    "serving": 5,
    "calories": 29,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 1,
    "fat": 2.5,
    "fiber": 0.6,
    "calcium": 13,
    "iron": 0.2,
    "potassium": 36,
    "selenium": 0,
    "omega3": 0,
    "note": "Portion controlled"
  },
  {
    "name": "Walnuts",
    "category": "Nut",
    "serving": 5,
    "calories": 33,
    "completeProtein": 0.8,
    "totalProtein": 0.8,
    "carbs": 0.7,
    "fat": 3.3,
    "fiber": 0.3,
    "calcium": 5,
    "iron": 0.1,
    "potassium": 22,
    "selenium": 0,
    "omega3": 0.45,
    "note": "Omega fats"
  },
  {
    "name": "Brazil Nut",
    "category": "Nut",
    "serving": 5,
    "calories": 33,
    "completeProtein": 0.7,
    "totalProtein": 0.7,
    "carbs": 0.6,
    "fat": 3.3,
    "fiber": 0.4,
    "calcium": 8,
    "iron": 0.1,
    "potassium": 33,
    "selenium": 95,
    "omega3": 0,
    "note": "1 nut"
  },
  {
    "name": "Pumpkin Seeds",
    "category": "Seed",
    "serving": 5,
    "calories": 28,
    "completeProtein": 1.5,
    "totalProtein": 1.5,
    "carbs": 1,
    "fat": 2,
    "fiber": 0.5,
    "calcium": 3,
    "iron": 0.4,
    "potassium": 40,
    "selenium": 0,
    "omega3": 0,
    "note": "Mineral add on"
  },
  {
    "name": "Lindt Excellence 85% Dark Chocolate",
    "category": "Sweet",
    "serving": 10,
    "calories": 58,
    "completeProtein": 1.2,
    "totalProtein": 1.2,
    "carbs": 2.2,
    "fat": 4.6,
    "fiber": 1.5,
    "calcium": 7,
    "iron": 1.1,
    "potassium": 72,
    "selenium": 1,
    "omega3": 0,
    "note": "1 square estimate, use label if different",
    "servingLabel": "1 square",
    "defaultMode": "servings"
  },
  {
    "name": "Dark Chocolate 90%",
    "category": "Sweet",
    "serving": 10,
    "calories": 59,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 1.4,
    "fat": 5.5,
    "fiber": 1.6,
    "calcium": 8,
    "iron": 1.2,
    "potassium": 80,
    "selenium": 1,
    "omega3": 0,
    "note": "High cocoa chocolate estimate",
    "servingLabel": "10g",
    "defaultMode": "grams"
  },
  {
    "name": "Cocoa Powder Unsweetened",
    "category": "Baking",
    "serving": 5,
    "calories": 12,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 3,
    "fat": 0.7,
    "fiber": 1.7,
    "calcium": 7,
    "iron": 0.7,
    "potassium": 76,
    "selenium": 0,
    "omega3": 0,
    "note": "1 tbsp",
    "servingLabel": "1 tbsp",
    "defaultMode": "servings"
  },
  {
    "name": "Rolled Oats Dry",
    "category": "Carb",
    "serving": 40,
    "calories": 150,
    "completeProtein": 5,
    "totalProtein": 5,
    "carbs": 27,
    "fat": 3,
    "fiber": 4,
    "calcium": 20,
    "iron": 1.7,
    "potassium": 150,
    "selenium": 11,
    "omega3": 0,
    "note": "1/2 cup dry",
    "servingLabel": "1/2 cup dry",
    "defaultMode": "servings"
  },
  {
    "name": "Quinoa Cooked",
    "category": "Carb",
    "serving": 100,
    "calories": 120,
    "completeProtein": 4.4,
    "totalProtein": 4.4,
    "carbs": 21,
    "fat": 1.9,
    "fiber": 2.8,
    "calcium": 17,
    "iron": 1.5,
    "potassium": 172,
    "selenium": 3,
    "omega3": 0,
    "note": "Cooked",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Orange",
    "category": "Fruit",
    "serving": 100,
    "calories": 47,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 12,
    "fat": 0,
    "fiber": 2.5,
    "calcium": 40,
    "iron": 0.1,
    "potassium": 180,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Grapefruit",
    "category": "Fruit",
    "serving": 100,
    "calories": 42,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 10,
    "fat": 0,
    "fiber": 1.5,
    "calcium": 20,
    "iron": 0.1,
    "potassium": 135,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Strawberries",
    "category": "Fruit",
    "serving": 100,
    "calories": 32,
    "completeProtein": 0.7,
    "totalProtein": 0.7,
    "carbs": 8,
    "fat": 0.3,
    "fiber": 2,
    "calcium": 16,
    "iron": 0.4,
    "potassium": 153,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Blueberries",
    "category": "Fruit",
    "serving": 100,
    "calories": 57,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 14,
    "fat": 0,
    "fiber": 2.5,
    "calcium": 6,
    "iron": 0.3,
    "potassium": 77,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Blackberries",
    "category": "Fruit",
    "serving": 35,
    "calories": 15,
    "completeProtein": 0.5,
    "totalProtein": 0.5,
    "carbs": 3,
    "fat": 0,
    "fiber": 2,
    "calcium": 10,
    "iron": 0.2,
    "potassium": 60,
    "selenium": 0,
    "omega3": 0,
    "note": "Your serving"
  },
  {
    "name": "Kiwi",
    "category": "Fruit",
    "serving": 100,
    "calories": 61,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 15,
    "fat": 0.5,
    "fiber": 3,
    "calcium": 34,
    "iron": 0.3,
    "potassium": 312,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw"
  },
  {
    "name": "Grapes",
    "category": "Fruit",
    "serving": 100,
    "calories": 69,
    "completeProtein": 0.7,
    "totalProtein": 0.7,
    "carbs": 18,
    "fat": 0.2,
    "fiber": 1,
    "calcium": 10,
    "iron": 0.4,
    "potassium": 190,
    "selenium": 0,
    "omega3": 0,
    "note": "Easy to overeat"
  },
  {
    "name": "Amla Raw",
    "category": "Fruit",
    "serving": 100,
    "calories": 44,
    "completeProtein": 0.9,
    "totalProtein": 0.9,
    "carbs": 10,
    "fat": 0.6,
    "fiber": 4.3,
    "calcium": 25,
    "iron": 0.3,
    "potassium": 198,
    "selenium": 0,
    "omega3": 0,
    "note": "Indian gooseberry, raw",
    "servingLabel": "100g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Amla Powder",
    "category": "Supplement",
    "serving": 5,
    "calories": 15,
    "completeProtein": 0.1,
    "totalProtein": 0.1,
    "carbs": 4,
    "fat": 0,
    "fiber": 2,
    "calcium": 8,
    "iron": 0.1,
    "potassium": 30,
    "selenium": 0,
    "omega3": 0,
    "note": "1 tsp powder estimate",
    "servingLabel": "1 tsp",
    "defaultMode": "servings"
  },
  {
    "name": "Apple Raw",
    "category": "Fruit",
    "serving": 100,
    "calories": 52,
    "completeProtein": 0.3,
    "totalProtein": 0.3,
    "carbs": 14,
    "fat": 0.2,
    "fiber": 2.4,
    "calcium": 6,
    "iron": 0.1,
    "potassium": 107,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw with skin",
    "servingLabel": "100g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Banana Raw",
    "category": "Fruit",
    "serving": 100,
    "calories": 89,
    "completeProtein": 1.1,
    "totalProtein": 1.1,
    "carbs": 23,
    "fat": 0.3,
    "fiber": 2.6,
    "calcium": 5,
    "iron": 0.3,
    "potassium": 358,
    "selenium": 1,
    "omega3": 0,
    "note": "Raw",
    "servingLabel": "100g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Pomegranate Arils",
    "category": "Fruit",
    "serving": 100,
    "calories": 83,
    "completeProtein": 1.7,
    "totalProtein": 1.7,
    "carbs": 19,
    "fat": 1.2,
    "fiber": 4,
    "calcium": 10,
    "iron": 0.3,
    "potassium": 236,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw arils",
    "servingLabel": "100g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Medjool Date",
    "category": "Fruit",
    "serving": 24,
    "calories": 66,
    "completeProtein": 0.4,
    "totalProtein": 0.4,
    "carbs": 18,
    "fat": 0,
    "fiber": 1.6,
    "calcium": 15,
    "iron": 0.2,
    "potassium": 167,
    "selenium": 0,
    "omega3": 0,
    "note": "1 date",
    "servingLabel": "1 date",
    "defaultMode": "servings"
  },
  {
    "name": "Ginger Raw",
    "category": "Spice",
    "serving": 5,
    "calories": 4,
    "completeProtein": 0.1,
    "totalProtein": 0.1,
    "carbs": 1,
    "fat": 0,
    "fiber": 0.1,
    "calcium": 1,
    "iron": 0,
    "potassium": 21,
    "selenium": 0,
    "omega3": 0,
    "note": "1 tsp grated",
    "servingLabel": "1 tsp grated",
    "defaultMode": "servings"
  },
  {
    "name": "Ginger Tea Unsweetened",
    "category": "Beverage",
    "serving": 250,
    "calories": 5,
    "completeProtein": 0,
    "totalProtein": 0,
    "carbs": 1,
    "fat": 0,
    "fiber": 0,
    "calcium": 2,
    "iron": 0,
    "potassium": 15,
    "selenium": 0,
    "omega3": 0,
    "note": "Water with ginger, no sugar",
    "servingLabel": "1 cup",
    "defaultMode": "servings"
  },
  {
    "name": "Amla Ginger Juice Unsweetened",
    "category": "Beverage",
    "serving": 250,
    "calories": 25,
    "completeProtein": 0.3,
    "totalProtein": 0.3,
    "carbs": 6,
    "fat": 0.1,
    "fiber": 1,
    "calcium": 12,
    "iron": 0.1,
    "potassium": 110,
    "selenium": 0,
    "omega3": 0,
    "note": "Amla ginger drink, no added sugar",
    "servingLabel": "1 cup",
    "defaultMode": "servings"
  },
  {
    "name": "Lemon Ginger Honey Drink",
    "category": "Beverage",
    "serving": 250,
    "calories": 35,
    "completeProtein": 0,
    "totalProtein": 0,
    "carbs": 9,
    "fat": 0,
    "fiber": 0,
    "calcium": 5,
    "iron": 0,
    "potassium": 25,
    "selenium": 0,
    "omega3": 0,
    "note": "Includes 1 tsp honey",
    "servingLabel": "1 cup",
    "defaultMode": "servings"
  },
  {
    "name": "Coconut Water",
    "category": "Beverage",
    "serving": 240,
    "calories": 45,
    "completeProtein": 0.5,
    "totalProtein": 0.5,
    "carbs": 11,
    "fat": 0,
    "fiber": 0,
    "calcium": 24,
    "iron": 0.3,
    "potassium": 400,
    "selenium": 0,
    "omega3": 0,
    "note": "Unsweetened",
    "servingLabel": "1 cup",
    "defaultMode": "servings"
  },
  {
    "name": "Carrot Raw",
    "category": "Vegetable",
    "serving": 50,
    "calories": 20,
    "completeProtein": 0.5,
    "totalProtein": 0.5,
    "carbs": 5,
    "fat": 0,
    "fiber": 1.5,
    "calcium": 15,
    "iron": 0.2,
    "potassium": 160,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw",
    "servingLabel": "50g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Celery Raw",
    "category": "Vegetable",
    "serving": 50,
    "calories": 8,
    "completeProtein": 0.3,
    "totalProtein": 0.3,
    "carbs": 1.5,
    "fat": 0,
    "fiber": 0.8,
    "calcium": 20,
    "iron": 0.1,
    "potassium": 130,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw",
    "servingLabel": "50g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Cucumber Raw",
    "category": "Vegetable",
    "serving": 100,
    "calories": 15,
    "completeProtein": 0.7,
    "totalProtein": 0.7,
    "carbs": 4,
    "fat": 0,
    "fiber": 0.5,
    "calcium": 16,
    "iron": 0.3,
    "potassium": 150,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw",
    "servingLabel": "100g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Tomato Raw",
    "category": "Vegetable",
    "serving": 100,
    "calories": 18,
    "completeProtein": 0.9,
    "totalProtein": 0.9,
    "carbs": 4,
    "fat": 0.2,
    "fiber": 1.2,
    "calcium": 10,
    "iron": 0.3,
    "potassium": 237,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw",
    "servingLabel": "100g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Onion Raw",
    "category": "Vegetable",
    "serving": 50,
    "calories": 20,
    "completeProtein": 0.6,
    "totalProtein": 0.6,
    "carbs": 5,
    "fat": 0,
    "fiber": 0.9,
    "calcium": 12,
    "iron": 0.1,
    "potassium": 73,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw",
    "servingLabel": "50g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Bell Pepper Raw",
    "category": "Vegetable",
    "serving": 100,
    "calories": 31,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 6,
    "fat": 0.3,
    "fiber": 2.1,
    "calcium": 7,
    "iron": 0.4,
    "potassium": 211,
    "selenium": 0,
    "omega3": 0,
    "note": "Raw",
    "servingLabel": "100g raw",
    "defaultMode": "grams"
  },
  {
    "name": "Broccoli Cooked",
    "category": "Vegetable",
    "serving": 100,
    "calories": 35,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 7,
    "fat": 0.4,
    "fiber": 3,
    "calcium": 47,
    "iron": 0.7,
    "potassium": 300,
    "selenium": 2,
    "omega3": 0,
    "note": "Cooked",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Cauliflower Cooked",
    "category": "Vegetable",
    "serving": 100,
    "calories": 23,
    "completeProtein": 1.8,
    "totalProtein": 1.8,
    "carbs": 4,
    "fat": 0.4,
    "fiber": 2.3,
    "calcium": 16,
    "iron": 0.3,
    "potassium": 142,
    "selenium": 1,
    "omega3": 0,
    "note": "Cooked",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Cabbage Cooked Plain",
    "category": "Vegetable",
    "serving": 100,
    "calories": 25,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 6,
    "fat": 0,
    "fiber": 3,
    "calcium": 40,
    "iron": 0.5,
    "potassium": 170,
    "selenium": 1,
    "omega3": 0,
    "note": "Plain cooked",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Zucchini Cooked",
    "category": "Vegetable",
    "serving": 100,
    "calories": 20,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 4,
    "fat": 0.3,
    "fiber": 1,
    "calcium": 16,
    "iron": 0.4,
    "potassium": 260,
    "selenium": 0,
    "omega3": 0,
    "note": "Cooked",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Mushrooms Cooked",
    "category": "Vegetable",
    "serving": 100,
    "calories": 28,
    "completeProtein": 3.6,
    "totalProtein": 3.6,
    "carbs": 4,
    "fat": 0.5,
    "fiber": 1,
    "calcium": 4,
    "iron": 0.5,
    "potassium": 356,
    "selenium": 18,
    "omega3": 0,
    "note": "Cooked",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Green Beans Cooked",
    "category": "Vegetable",
    "serving": 100,
    "calories": 35,
    "completeProtein": 1.9,
    "totalProtein": 1.9,
    "carbs": 8,
    "fat": 0.3,
    "fiber": 3.2,
    "calcium": 44,
    "iron": 0.7,
    "potassium": 146,
    "selenium": 0,
    "omega3": 0,
    "note": "Cooked",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Peas Cooked",
    "category": "Vegetable",
    "serving": 100,
    "calories": 84,
    "completeProtein": 5.4,
    "totalProtein": 5.4,
    "carbs": 15,
    "fat": 0.4,
    "fiber": 5.5,
    "calcium": 27,
    "iron": 1.5,
    "potassium": 271,
    "selenium": 2,
    "omega3": 0,
    "note": "Cooked",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Corn Cooked",
    "category": "Vegetable",
    "serving": 100,
    "calories": 96,
    "completeProtein": 3.4,
    "totalProtein": 3.4,
    "carbs": 21,
    "fat": 1.5,
    "fiber": 2.4,
    "calcium": 3,
    "iron": 0.5,
    "potassium": 218,
    "selenium": 1,
    "omega3": 0,
    "note": "Cooked kernels",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Potato Boiled",
    "category": "Carb",
    "serving": 100,
    "calories": 87,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 20,
    "fat": 0.1,
    "fiber": 1.8,
    "calcium": 5,
    "iron": 0.3,
    "potassium": 379,
    "selenium": 0,
    "omega3": 0,
    "note": "Boiled plain",
    "servingLabel": "100g boiled",
    "defaultMode": "grams"
  },
  {
    "name": "Sweet Potato Boiled",
    "category": "Carb",
    "serving": 100,
    "calories": 76,
    "completeProtein": 1.4,
    "totalProtein": 1.4,
    "carbs": 18,
    "fat": 0.1,
    "fiber": 2.5,
    "calcium": 27,
    "iron": 0.7,
    "potassium": 230,
    "selenium": 1,
    "omega3": 0,
    "note": "Boiled plain",
    "servingLabel": "100g boiled",
    "defaultMode": "grams"
  },
  {
    "name": "Spinach Cooked",
    "category": "Greens",
    "serving": 100,
    "calories": 23,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 4,
    "fat": 0.3,
    "fiber": 2.4,
    "calcium": 136,
    "iron": 3.6,
    "potassium": 466,
    "selenium": 1,
    "omega3": 0,
    "note": "Cooked greens",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Drumstick Leaves Cooked",
    "category": "Greens",
    "serving": 100,
    "calories": 64,
    "completeProtein": 6.7,
    "totalProtein": 6.7,
    "carbs": 9,
    "fat": 1.4,
    "fiber": 2,
    "calcium": 185,
    "iron": 4,
    "potassium": 337,
    "selenium": 1,
    "omega3": 0,
    "note": "Murungai keerai estimate",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Queen of Greens Salad",
    "category": "Greens",
    "serving": 150,
    "calories": 120,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 10,
    "fat": 7,
    "fiber": 3,
    "calcium": 60,
    "iron": 1.4,
    "potassium": 300,
    "selenium": 1,
    "omega3": 0.1,
    "note": "Estimated mixed greens salad",
    "servingLabel": "1 salad",
    "defaultMode": "servings"
  },
  {
    "name": "Adai",
    "category": "South Indian Breakfast",
    "serving": 100,
    "calories": 210,
    "completeProtein": 9,
    "totalProtein": 9,
    "carbs": 30,
    "fat": 6,
    "fiber": 5,
    "calcium": 40,
    "iron": 2,
    "potassium": 200,
    "selenium": 3,
    "omega3": 0,
    "note": "Lentil dosa, oil dependent",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Appam",
    "category": "South Indian Breakfast",
    "serving": 100,
    "calories": 180,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 35,
    "fat": 3,
    "fiber": 1,
    "calcium": 10,
    "iron": 0.5,
    "potassium": 90,
    "selenium": 1,
    "omega3": 0,
    "note": "Rice coconut batter",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Pesarattu",
    "category": "South Indian Breakfast",
    "serving": 100,
    "calories": 180,
    "completeProtein": 8,
    "totalProtein": 8,
    "carbs": 28,
    "fat": 4,
    "fiber": 4,
    "calcium": 30,
    "iron": 2,
    "potassium": 180,
    "selenium": 3,
    "omega3": 0,
    "note": "Green gram dosa",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Rava Upma",
    "category": "South Indian Breakfast",
    "serving": 100,
    "calories": 150,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 25,
    "fat": 4,
    "fiber": 2,
    "calcium": 20,
    "iron": 1,
    "potassium": 120,
    "selenium": 2,
    "omega3": 0,
    "note": "Oil dependent",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Uthappam",
    "category": "South Indian Breakfast",
    "serving": 100,
    "calories": 170,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 30,
    "fat": 4,
    "fiber": 2,
    "calcium": 20,
    "iron": 1,
    "potassium": 120,
    "selenium": 2,
    "omega3": 0,
    "note": "Oil dependent",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Chapathi",
    "category": "South Indian Breakfast",
    "serving": 60,
    "calories": 110,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 21,
    "fat": 2,
    "fiber": 3,
    "calcium": 15,
    "iron": 1,
    "potassium": 90,
    "selenium": 2,
    "omega3": 0,
    "note": "1 medium",
    "servingLabel": "1 chapathi",
    "defaultMode": "servings"
  },
  {
    "name": "Poori",
    "category": "South Indian Breakfast",
    "serving": 40,
    "calories": 120,
    "completeProtein": 2.5,
    "totalProtein": 2.5,
    "carbs": 15,
    "fat": 6,
    "fiber": 1.5,
    "calcium": 10,
    "iron": 0.8,
    "potassium": 60,
    "selenium": 1,
    "omega3": 0,
    "note": "1 medium fried poori",
    "servingLabel": "1 poori",
    "defaultMode": "servings"
  },
  {
    "name": "Parotta",
    "category": "South Indian Breakfast",
    "serving": 80,
    "calories": 260,
    "completeProtein": 6,
    "totalProtein": 6,
    "carbs": 36,
    "fat": 10,
    "fiber": 2,
    "calcium": 20,
    "iron": 1.5,
    "potassium": 120,
    "selenium": 4,
    "omega3": 0,
    "note": "1 parotta estimate",
    "servingLabel": "1 parotta",
    "defaultMode": "servings"
  },
  {
    "name": "Rava Dosa",
    "category": "South Indian Breakfast",
    "serving": 100,
    "calories": 190,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 32,
    "fat": 5,
    "fiber": 2,
    "calcium": 20,
    "iron": 1,
    "potassium": 120,
    "selenium": 2,
    "omega3": 0,
    "note": "Crisp dosa, oil dependent",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Lemon Rice",
    "category": "South Indian Rice",
    "serving": 100,
    "calories": 175,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 28,
    "fat": 6,
    "fiber": 1.5,
    "calcium": 15,
    "iron": 0.8,
    "potassium": 100,
    "selenium": 2,
    "omega3": 0,
    "note": "Oil and peanuts vary",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Curd Rice",
    "category": "South Indian Rice",
    "serving": 100,
    "calories": 130,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 20,
    "fat": 3,
    "fiber": 0.5,
    "calcium": 90,
    "iron": 0.3,
    "potassium": 120,
    "selenium": 2,
    "omega3": 0,
    "note": "Yogurt rice estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Tamarind Rice Puliyogare",
    "category": "South Indian Rice",
    "serving": 100,
    "calories": 190,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 30,
    "fat": 7,
    "fiber": 2,
    "calcium": 20,
    "iron": 1,
    "potassium": 120,
    "selenium": 2,
    "omega3": 0,
    "note": "Oil and peanuts vary",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Tomato Rice",
    "category": "South Indian Rice",
    "serving": 100,
    "calories": 165,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 28,
    "fat": 5,
    "fiber": 2,
    "calcium": 20,
    "iron": 0.8,
    "potassium": 150,
    "selenium": 2,
    "omega3": 0,
    "note": "Oil dependent",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Beetroot Pulao",
    "category": "Indian Rice",
    "serving": 100,
    "calories": 160,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 29,
    "fat": 4,
    "fiber": 3,
    "calcium": 25,
    "iron": 1,
    "potassium": 180,
    "selenium": 2,
    "omega3": 0,
    "note": "Home-style estimate, oil dependent",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Vegetable Pulao",
    "category": "Indian Rice",
    "serving": 100,
    "calories": 170,
    "completeProtein": 3.5,
    "totalProtein": 3.5,
    "carbs": 29,
    "fat": 5,
    "fiber": 2.5,
    "calcium": 25,
    "iron": 1,
    "potassium": 160,
    "selenium": 2,
    "omega3": 0,
    "note": "Home-style estimate, oil dependent",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Vegetable Biryani",
    "category": "Indian Rice",
    "serving": 100,
    "calories": 190,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 30,
    "fat": 7,
    "fiber": 3,
    "calcium": 35,
    "iron": 1.2,
    "potassium": 180,
    "selenium": 3,
    "omega3": 0,
    "note": "Biryani estimate, oil/ghee dependent",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Mushroom Biryani",
    "category": "Indian Rice",
    "serving": 100,
    "calories": 185,
    "completeProtein": 4.5,
    "totalProtein": 4.5,
    "carbs": 29,
    "fat": 6.5,
    "fiber": 2.5,
    "calcium": 25,
    "iron": 1.1,
    "potassium": 220,
    "selenium": 6,
    "omega3": 0,
    "note": "Mushroom biryani estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Chicken Biryani",
    "category": "Indian Rice",
    "serving": 100,
    "calories": 215,
    "completeProtein": 9,
    "totalProtein": 9,
    "carbs": 25,
    "fat": 8,
    "fiber": 1.5,
    "calcium": 25,
    "iron": 1.1,
    "potassium": 180,
    "selenium": 8,
    "omega3": 0,
    "note": "Chicken biryani estimate, oil/ghee dependent",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Egg Biryani",
    "category": "Indian Rice",
    "serving": 100,
    "calories": 210,
    "completeProtein": 7,
    "totalProtein": 7,
    "carbs": 27,
    "fat": 8,
    "fiber": 1.5,
    "calcium": 35,
    "iron": 1.4,
    "potassium": 160,
    "selenium": 8,
    "omega3": 0,
    "note": "Egg biryani estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Tofu Cooked",
    "category": "Protein",
    "serving": 100,
    "calories": 95,
    "completeProtein": 10,
    "totalProtein": 10,
    "carbs": 3,
    "fat": 5,
    "fiber": 1,
    "calcium": 180,
    "iron": 2,
    "potassium": 140,
    "selenium": 8,
    "omega3": 0.1,
    "note": "Cooked firm tofu estimate",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Air Fried Tofu",
    "category": "Protein",
    "serving": 100,
    "calories": 130,
    "completeProtein": 13,
    "totalProtein": 13,
    "carbs": 4,
    "fat": 7,
    "fiber": 1,
    "calcium": 220,
    "iron": 2.5,
    "potassium": 180,
    "selenium": 10,
    "omega3": 0.1,
    "note": "Air fried firm tofu, light oil estimate",
    "servingLabel": "100g cooked",
    "defaultMode": "grams"
  },
  {
    "name": "Cabbage Poriyal",
    "category": "Poriyal",
    "serving": 100,
    "calories": 80,
    "completeProtein": 2,
    "totalProtein": 2,
    "carbs": 9,
    "fat": 4,
    "fiber": 4,
    "calcium": 45,
    "iron": 0.8,
    "potassium": 210,
    "selenium": 1,
    "omega3": 0,
    "note": "Cabbage coconut poriyal estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Aloo Paratha",
    "category": "Indian Bread",
    "serving": 120,
    "calories": 290,
    "completeProtein": 7,
    "totalProtein": 7,
    "carbs": 45,
    "fat": 9,
    "fiber": 5,
    "calcium": 35,
    "iron": 2,
    "potassium": 350,
    "selenium": 8,
    "omega3": 0,
    "note": "1 medium stuffed paratha estimate",
    "servingLabel": "1 paratha",
    "defaultMode": "servings"
  },
  {
    "name": "Paneer Paratha",
    "category": "Indian Bread",
    "serving": 120,
    "calories": 330,
    "completeProtein": 13,
    "totalProtein": 13,
    "carbs": 36,
    "fat": 15,
    "fiber": 4,
    "calcium": 180,
    "iron": 1.8,
    "potassium": 220,
    "selenium": 8,
    "omega3": 0,
    "note": "1 medium paneer paratha estimate",
    "servingLabel": "1 paratha",
    "defaultMode": "servings"
  },
  {
    "name": "Stuffed Aloo Paratha",
    "category": "Indian Bread",
    "serving": 140,
    "calories": 340,
    "completeProtein": 8,
    "totalProtein": 8,
    "carbs": 52,
    "fat": 11,
    "fiber": 6,
    "calcium": 40,
    "iron": 2.3,
    "potassium": 420,
    "selenium": 9,
    "omega3": 0,
    "note": "Larger stuffed aloo paratha estimate",
    "servingLabel": "1 stuffed paratha",
    "defaultMode": "servings"
  },
  {
    "name": "Stuffed Paneer Paratha",
    "category": "Indian Bread",
    "serving": 140,
    "calories": 390,
    "completeProtein": 16,
    "totalProtein": 16,
    "carbs": 42,
    "fat": 18,
    "fiber": 5,
    "calcium": 230,
    "iron": 2.1,
    "potassium": 260,
    "selenium": 10,
    "omega3": 0,
    "note": "Larger stuffed paneer paratha estimate",
    "servingLabel": "1 stuffed paratha",
    "defaultMode": "servings"
  },
  {
    "name": "Rasam",
    "category": "Curry",
    "serving": 100,
    "calories": 35,
    "completeProtein": 1.5,
    "totalProtein": 1.5,
    "carbs": 5,
    "fat": 1,
    "fiber": 1,
    "calcium": 20,
    "iron": 0.6,
    "potassium": 140,
    "selenium": 1,
    "omega3": 0,
    "note": "Tomato tamarind rasam estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Bisibele Bath",
    "category": "South Indian Rice",
    "serving": 100,
    "calories": 160,
    "completeProtein": 5,
    "totalProtein": 5,
    "carbs": 25,
    "fat": 4,
    "fiber": 4,
    "calcium": 35,
    "iron": 1.5,
    "potassium": 220,
    "selenium": 3,
    "omega3": 0,
    "note": "Rice dal vegetable estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Moong Dal Khichdi",
    "category": "Indian Rice",
    "serving": 100,
    "calories": 120,
    "completeProtein": 5,
    "totalProtein": 5,
    "carbs": 20,
    "fat": 3,
    "fiber": 3,
    "calcium": 25,
    "iron": 1.3,
    "potassium": 180,
    "selenium": 3,
    "omega3": 0,
    "note": "Rice moong dal khichdi estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Vegetable Kurma",
    "category": "Curry",
    "serving": 100,
    "calories": 125,
    "completeProtein": 3,
    "totalProtein": 3,
    "carbs": 12,
    "fat": 8,
    "fiber": 3,
    "calcium": 45,
    "iron": 1,
    "potassium": 220,
    "selenium": 2,
    "omega3": 0,
    "note": "Coconut/cashew gravy estimate",
    "servingLabel": "100g",
    "defaultMode": "grams"
  },
  {
    "name": "Coconut Chutney",
    "category": "Condiment",
    "serving": 30,
    "calories": 70,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 4,
    "fat": 6,
    "fiber": 1,
    "calcium": 8,
    "iron": 0.4,
    "potassium": 60,
    "selenium": 1,
    "omega3": 0,
    "note": "Fat source",
    "servingLabel": "30g",
    "defaultMode": "grams"
  },
  {
    "name": "Tomato Chutney",
    "category": "Condiment",
    "serving": 30,
    "calories": 35,
    "completeProtein": 1,
    "totalProtein": 1,
    "carbs": 5,
    "fat": 1,
    "fiber": 1,
    "calcium": 10,
    "iron": 0.4,
    "potassium": 90,
    "selenium": 1,
    "omega3": 0,
    "note": "Oil dependent",
    "servingLabel": "30g",
    "defaultMode": "grams"
  },
  {
    "name": "Sriracha",
    "category": "Condiment",
    "serving": 5,
    "calories": 5,
    "completeProtein": 0,
    "totalProtein": 0,
    "carbs": 1,
    "fat": 0,
    "fiber": 0,
    "calcium": 0,
    "iron": 0,
    "potassium": 5,
    "selenium": 0,
    "omega3": 0,
    "note": "1 tsp",
    "servingLabel": "1 tsp",
    "defaultMode": "servings"
  },
  {
    "name": "Cheddar Cheese",
    "category": "Dairy Fat",
    "serving": 28,
    "calories": 115,
    "completeProtein": 7,
    "totalProtein": 7,
    "carbs": 0.5,
    "fat": 9.5,
    "fiber": 0,
    "calcium": 200,
    "iron": 0.2,
    "potassium": 28,
    "selenium": 4,
    "omega3": 0,
    "note": "1 oz",
    "servingLabel": "1 oz",
    "defaultMode": "servings"
  },
  {
    "name": "Mozzarella Cheese",
    "category": "Dairy Fat",
    "serving": 28,
    "calories": 85,
    "completeProtein": 6,
    "totalProtein": 6,
    "carbs": 1,
    "fat": 6,
    "fiber": 0,
    "calcium": 143,
    "iron": 0.1,
    "potassium": 22,
    "selenium": 4,
    "omega3": 0,
    "note": "1 oz part skim estimate",
    "servingLabel": "1 oz",
    "defaultMode": "servings"
  },
  {
    "name": "Cheese Slice",
    "category": "Dairy Fat",
    "serving": 21,
    "calories": 60,
    "completeProtein": 4,
    "totalProtein": 4,
    "carbs": 2,
    "fat": 4,
    "fiber": 0,
    "calcium": 120,
    "iron": 0.1,
    "potassium": 40,
    "selenium": 3,
    "omega3": 0,
    "note": "1 processed slice",
    "servingLabel": "1 slice",
    "defaultMode": "servings"
  },
  {
    "name": "Gold Standard Whey",
    "category": "Supplement",
    "serving": 32,
    "calories": 120,
    "completeProtein": 24,
    "totalProtein": 24,
    "carbs": 3,
    "fat": 1,
    "fiber": 0,
    "calcium": 130,
    "iron": 0.9,
    "potassium": 200,
    "selenium": 0,
    "omega3": 0,
    "note": "1 scoop"
  },
  {
    "name": "Omega 3 Fish Oil",
    "category": "Supplement",
    "serving": 1,
    "calories": 10,
    "completeProtein": 0,
    "totalProtein": 0,
    "carbs": 0,
    "fat": 1,
    "fiber": 0,
    "calcium": 0,
    "iron": 0,
    "potassium": 0,
    "selenium": 0,
    "omega3": 0.3,
    "note": "1 softgel estimate, check label for EPA/DHA",
    "servingLabel": "1 softgel",
    "defaultMode": "servings"
  },
  {
    "name": "Magnesium Glycinate",
    "category": "Supplement",
    "serving": 1,
    "calories": 0,
    "completeProtein": 0,
    "totalProtein": 0,
    "carbs": 0,
    "fat": 0,
    "fiber": 0,
    "calcium": 0,
    "iron": 0,
    "magnesium": 200,
    "potassium": 0,
    "sodium": 0,
    "selenium": 0,
    "omega3": 0,
    "vitaminD": 0,
    "note": "1 capsule, 200 mg elemental magnesium estimate",
    "servingLabel": "1 capsule",
    "defaultMode": "servings"
  },
  {
    "name": "Vitamin D3",
    "category": "Supplement",
    "serving": 1,
    "calories": 0,
    "completeProtein": 0,
    "totalProtein": 0,
    "carbs": 0,
    "fat": 0,
    "fiber": 0,
    "calcium": 0,
    "iron": 0,
    "magnesium": 0,
    "potassium": 0,
    "sodium": 0,
    "selenium": 0,
    "omega3": 0,
    "vitaminD": 25,
    "note": "1 capsule, 25 mcg / 1000 IU estimate",
    "servingLabel": "1 capsule",
    "defaultMode": "servings"
  },
  {
    "name": "Collagen Organika",
    "category": "Supplement",
    "serving": 10,
    "calories": 35,
    "completeProtein": 0,
    "totalProtein": 9,
    "carbs": 0,
    "fat": 0,
    "fiber": 0,
    "calcium": 0,
    "iron": 0,
    "potassium": 0,
    "selenium": 0,
    "omega3": 0,
    "note": "Incomplete protein"
  }
];
